#!/usr/bin/env bash

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

echo >> /Users/emar/.zprofile
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/emar/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

